format:
  pdf:
    pdf-engine: pdflatex
    toc: false
    keep-tex: true
    number-sections: true
    colorlinks: true
    cite-method: biblatex
    include-in-header: 
      - preamble/text-style.tex # strictly req'd, for dbl spacing?
      - preamble/cmds.tex       # req'd for now (\Notes)
      - preamble/fonts.tex
      - preamble/floats.tex
      - preamble/bib.tex
        # - assets/comments.tex

